### ISSUE TITLE
Can this add-in be used with Eclipse version 2021.0 ?

### ISSUE THREAD

**Issue by martinboers** [PLCnext/PLCnext_CLI_Eclipse#3]
Question from a customer:
> The version Eclipse 2021.0 was not compatible with the PLCnCLI and SDK from the download area on your site.
Why is that?

(internal ref 210895)

**Comment by mluhmann** [comment]
The PLCnCLI included IDE plugins are always tested with the latest version of Eclipse/Visual Studio. **Latest version** in this case means, it was released before our release.

In case of this example: 
Eclipse 2020.12 was released in December last year --> our Version 2021.0 works
Eclipse 2021.0 **does not exist**
Eclipse 2021.3 was released in March 2021 --> after our release and officially not supported. It might work, but it's untested from our site.
